version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Build
          command: npm run build

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Deploy to $DEPLOY_ENV Environment
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              DEPLOY_ENV="Prod"
            elif [ "$CIRCLE_BRANCH" == "preprod" ]; then
              DEPLOY_ENV="Preprod"
            else
              DEPLOY_ENV="QA"
            fi
            npm run deploy:$DEPLOY_ENV

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
